### ISSUE TITLE
When is full dataset availabe?

### ISSUE THREAD

**Issue by cscyangj** [holistic-video-understanding/HVU-Downloader#1]
We can get Mini dataset now, so when is the full version available?

Thanks

**Comment by RezaBehzadpour** [comment]
By the [end of October][1].

[1]: https://github.com/holistic-video-understanding/Mini-HVU/issues/2#issuecomment-535448975

**Comment by MohsenFayyaz89** [comment]
The full HVU dataset is available at https://github.com/holistic-video-understanding/HVU-Dataset
