### ISSUE TITLE
The downlowding is too slow. 

### ISSUE THREAD

**Issue by jeff62802217** [holistic-video-understanding/HVU-Downloader#4]
I used your downloader to download the HVU Dataset and it runs without error. However, the downloading seems to stop, the storage of output directory maintained 4KB and haven't changed. Does anybody come across the same problem? And what I should do to improve this situation?

**Comment by jeff62802217** [comment]
I input the command
python HVU_download.py /home/notebook/code/personal/HVU_Val_V1.0.csv /home/oppoer/work/HVU_val

and the terminal didn't output anything

**Comment by ThanisornBest** [comment]
I have the same problem

**Comment by MohsenFayyaz89** [comment]
https://github.com/holistic-video-understanding/HVU-Dataset#accessing-missing-videos-and-test-videos
